name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install pnpm
        working-directory: ./backend
        run: npm install -g pnpm
      - name: Install dependencies
        working-directory: ./backend
        run: pnpm install
      - name: Run Migrations
        working-directory: ./backend
        run: pnpm migrate